#!/usr/bin/env python3
import sys
sys.path.append('lib')

# I dislike Marco's import format because flake8 hates it <3
from charms.reactive import main
from charms.reactive import set_state
from charms.reactive import remove_state
from charmhelpers.core.hookenv import action_fail


set_state('vpe.add-route')

try:
    main()
except Exception as e:
    action_fail(repr(e))
finally:
    remove_state('vpe.add-route')
